import os
import sys

try:
    from PIL import Image
except ImportError:
    import subprocess
    subprocess.check_call([sys.executable, "-m", "pip", "install", "Pillow"])
    from PIL import Image

# Palette
COLORS = {
    'T': (0, 0, 0, 0),        
    'B': (0, 0, 0, 255),      
    'R': (255, 0, 0, 255),    
    'O': (255, 128, 0, 255),  
    'Y': (255, 255, 0, 255),  
    'S': (255, 204, 153, 255),
    'U': (0, 0, 255, 255),    
    'W': (255, 255, 255, 255),
    'G': (0, 180, 0, 255),    
    'D': (139, 69, 19, 255),  
    'L': (205, 133, 63, 255), 
    'C': (92, 148, 252, 255), # Classic Sky Blue
    'P': (252, 152, 56, 255), # Peach/Orange tone
    'E': (200, 76, 12, 255),  # Brick Red
}

# --- Player Frames (16x16) ---
mario_idle = [
    "TTTTTRRRRRTTTTTT",
    "TTTTRRRRRRRRRTTT",
    "TTTTDDSDSSSTTTTT",
    "TTTDSDDSSDSSTTTT",
    "TTTDSDSSDSSSSTTT",
    "TTTDDSSSSDDDDTTT",
    "TTTTTTSSSSSTTTTT",
    "TTTTRRUUURRTTTTT",
    "TTTRRRUUURRRTTTT",
    "TTRRRRUUUURRRRTT",
    "TTSSYRUYURYSSTTT",
    "TTSSSOUUOUUSSTTT",
    "TTTSSUUUUUUSTTTT",
    "TTTTUUUUUUUTTTTT",
    "TTTDDDTTTDDTTTTT",
    "TTDDDDTTTDDDTTTT"
]

mario_walk1 = [
    "TTTTTRRRRRTTTTTT",
    "TTTTRRRRRRRRRTTT",
    "TTTTDDSDSSSTTTTT",
    "TTTDSDDSSDSSTTTT",
    "TTTDSDSSDSSSSTTT",
    "TTTDDSSSSDDDDTTT",
    "TTTTTTSSSSSTTTTT",
    "TTTTRRUUUUTTTTTT",
    "TTTRRRUUUUURRTTT",
    "TTRRRRUUUUURRRTT",
    "TTSSYRUYUUUUSSTT",
    "TTSSSOUUUUUSSTTT",
    "TTTSSUUUUUUTTTTT",
    "TTTTTUUUUTTTTTTT",
    "TTTDDDTTDDTTTTTT",
    "TTDDDDTTTDDDTTTT"
]

mario_walk2 = [
    "TTTTTRRRRRTTTTTT",
    "TTTTRRRRRRRRRTTT",
    "TTTTDDSDSSSTTTTT",
    "TTTDSDDSSDSSTTTT",
    "TTTDSDSSDSSSSTTT",
    "TTTDDSSSSDDDDTTT",
    "TTTTTTSSSSSTTTTT",
    "TTTTTRRUUURRTTTT",
    "TTTTRRRUUURRRTTT",
    "TTTRRRRUUUURRRRT",
    "TTTSSYRUYURYSSST",
    "TTTSSSOUUOUUSSST",
    "TTTTSSUUUUUUSTTT",
    "TTTTTUUUUUUUTTTT",
    "TTTTTDDTTTDDDTTT",
    "TTTTDDDTTTDDDDTT"
]

mario_jump = [
    "TTTTTRRRRRTTTTTT",
    "TTTTRRRRRRRRRTTT",
    "TTTTDDSDSSSTTTTT",
    "TTTDSDDSSDSSTTTT",
    "TTTDSDSSDSSSSTTT",
    "TTTDDSSSSDDDDTTT",
    "TTTTTTSSSSSTTTTT",
    "TTTTRRRUUTTTTTTT",
    "TTRRRRRUUURRRTTT",
    "TRRRRRRUUUURRRTT",
    "TTSSYRUYUYURSSTT",
    "TTSSSOUUOUUUSSTT",
    "TTTSSUUUUUUUSTTT",
    "TTTTUUUUUUUTTTTT",
    "TTTDDDTTTDDDTTTT",
    "TTDDDDTTTDDDDTTT"
]

# --- Enemy Frames (16x16 / 16x24) ---
# Classic Goomba 1
goomba_1 = [
    "TTTTTTTTTTTTTTTT",
    "TTTTTTTTTTTTTTTT",
    "TTTTTTDDDDTTTTTT",
    "TTTTDDLLLLDDTTTT",
    "TTDDLLLLLLLLDDTT",
    "TDLLBBLLLLBBLLDT",
    "TDLWWBLLLLBWWLDT",
    "TDLWWLLLLLLWWLDT",
    "TDLLLLDDDDLLLLDT",
    "TDLLLLLLLLLLLLDT",
    "TTDDLLLLLLLLDDTT",
    "TTTTDDDDDDDDTTTT",
    "TTTTTSDDDSSTTTTT",
    "TTTTSSDDDSSSTTTT",
    "TTTBBBDDDBBBTTTT",
    "TBBBBBTTTBBBBBTT",
    "TTTTTTTTTTTTTTTT",
    "TTTTTTTTTTTTTTTT",
    "TTTTTTTTTTTTTTTT",
    "TTTTTTTTTTTTTTTT",
    "TTTTTTTTTTTTTTTT",
    "TTTTTTTTTTTTTTTT",
    "TTTTTTTTTTTTTTTT",
    "TTTTTTTTTTTTTTTT"
]
# Classic Goomba 2
goomba_2 = [
    "TTTTTTTTTTTTTTTT",
    "TTTTTTTTTTTTTTTT",
    "TTTTTTDDDDTTTTTT",
    "TTTTDDLLLLDDTTTT",
    "TTDDLLLLLLLLDDTT",
    "TDLLBBLLLLBBLLDT",
    "TDLWWBLLLLBWWLDT",
    "TDLWWLLLLLLWWLDT",
    "TDLLLLDDDDLLLLDT",
    "TDLLLLLLLLLLLLDT",
    "TTDDLLLLLLLLDDTT",
    "TTTTDDDDDDDDTTTT",
    "TTTTTSDDDSSTTTTT",
    "TTTTSSDDDSSSTTTT",
    "TTBBBDDDDDDBBTTT",
    "TBBBBBBTTTBBBTTT",
    "TTTTTTTTTTTTTTTT",
    "TTTTTTTTTTTTTTTT",
    "TTTTTTTTTTTTTTTT",
    "TTTTTTTTTTTTTTTT",
    "TTTTTTTTTTTTTTTT",
    "TTTTTTTTTTTTTTTT",
    "TTTTTTTTTTTTTTTT",
    "TTTTTTTTTTTTTTTT"
]
# Koopa 1 (16x24)
koopa_1 = [
    "TTTTTGGGGGTTTTTT",
    "TTTGGYYYYYGGTTTT",
    "TTGYYYBBBYYYGTTT",
    "TGYYYWWWWBYYYGTT",
    "TGYYYYWWWWYYYGTT",
    "TTGYYYYYYYYYGTTT",
    "TTTGGYYYYYGGTTTT",
    "TTTTGGBBBGGTTTTT",
    "TTTGGGDDDDGGGTTT",
    "TTGGGGDDDGGGGGTT",
    "TGGGGDDDDDDGGGGT",
    "TGGYGGDDDDGGYGGT",
    "TGGYGGDDDDGGYGGT",
    "TGGYYGDDDDGYYGGT",
    "TTGGYYDDDDYYGGTT",
    "TTTGGYDDDDYGGTTT",
    "TTTTGGGGGGGGTTTT",
    "TTTTGGGGGGGGTTTT",
    "TTTTTGGTTGGTTTTT",
    "TTTTTGGTTGGTTTTT",
    "TTTLLLLTTLLLLTTT",
    "TTLLLLLLTLLLLLLT",
    "TTTTTTTTTTTTTTTT",
    "TTTTTTTTTTTTTTTT"
]
# Koopa 2 (16x24)
koopa_2 = [
    "TTTTTGGGGGTTTTTT",
    "TTTGGYYYYYGGTTTT",
    "TTGYYYBBBYYYGTTT",
    "TGYYYWWWWBYYYGTT",
    "TGYYYYWWWWYYYGTT",
    "TTGYYYYYYYYYGTTT",
    "TTTGGYYYYYGGTTTT",
    "TTTTGGBBBGGTTTTT",
    "TTTGGGDDDDGGGTTT",
    "TTGGGGDDDGGGGGTT",
    "TGGGGDDDDDDGGGGT",
    "TGGYGGDDDDGGYGGT",
    "TGGYGGDDDDGGYGGT",
    "TGGYYGDDDDGYYGGT",
    "TTGGYYDDDDYYGGTT",
    "TTTGGYDDDDYGGTTT",
    "TTTTGGGGGGGGTTTT",
    "TTTTGGGGGGGGTTTT",
    "TTTTTGGTTGGTTTTT",
    "TTTLLLLTTLLLLTTT",
    "TTLLLLLLTLLLLLLT",
    "TTTTTTTTTTTTTTTT",
    "TTTTTTTTTTTTTTTT",
    "TTTTTTTTTTTTTTTT"
]

# --- Items (16x16) ---
coin_1 = [
    "TTTTTTYYYYTTTTTT",
    "TTTTYYYYYYYYTTTT",
    "TTTYYTTYYTTYYTTT",
    "TTYYTTTYYTTTYYTT",
    "TTYYTTTYYTTTYYTT",
    "TYYTTTTYYTTTTYYT",
    "TYYTTTTYYTTTTYYT",
    "TYYTTTTYYTTTTYYT",
    "TYYTTTTYYTTTTYYT",
    "TYYTTTTYYTTTTYYT",
    "TYYTTTTYYTTTTYYT",
    "TTYYTTTYYTTTYYTT",
    "TTYYTTTYYTTTYYTT",
    "TTTYYTTYYTTYYTTT",
    "TTTTYYYYYYYYTTTT",
    "TTTTTTYYYYTTTTTT"
]
coin_2 = [
    "TTTTTTTYYTTTTTTT",
    "TTTTTTYYYYTTTTTT",
    "TTTTTYYTYYTTTTTT",
    "TTTTYYTTTYYTTTTT",
    "TTTTYYTTTYYTTTTT",
    "TTTYYTTTTTYYTTTT",
    "TTTYYTTTTTYYTTTT",
    "TTTYYTTTTTYYTTTT",
    "TTTYYTTTTTYYTTTT",
    "TTTYYTTTTTYYTTTT",
    "TTTYYTTTTTYYTTTT",
    "TTTTYYTTTYYTTTTT",
    "TTTTYYTTTYYTTTTT",
    "TTTTTYYTYYTTTTTT",
    "TTTTTTYYYYTTTTTT",
    "TTTTTTTYYTTTTTTT"
]
coin_3 = [
    "TTTTTTTTTTTTTTTT",
    "TTTTTTTYYTTTTTTT",
    "TTTTTTYYYYTTTTTT",
    "TTTTTTYYYYTTTTTT",
    "TTTTTTYYYYTTTTTT",
    "TTTTTTYYYYTTTTTT",
    "TTTTTTYYYYTTTTTT",
    "TTTTTTYYYYTTTTTT",
    "TTTTTTYYYYTTTTTT",
    "TTTTTTYYYYTTTTTT",
    "TTTTTTYYYYTTTTTT",
    "TTTTTTYYYYTTTTTT",
    "TTTTTTYYYYTTTTTT",
    "TTTTTTTYYTTTTTTT",
    "TTTTTTTTTTTTTTTT",
    "TTTTTTTTTTTTTTTT"
]
mushroom = [
    "TTTTTTBBBBTTTTTT",
    "TTTTBBRRRRBBTTTT",
    "TTTBRRRRRRRRBTTT",
    "TTBRRWWWWWWWRBTT",
    "TBRRWWWWWWWWWRBT",
    "TBRRWWWWWWWWWRBT",
    "TBRRWWWWWWWWWRBT",
    "TBRRRWWWWWWWRRBT",
    "TBRRRRRRRRRRRRBT",
    "TTBRRRRRRRRRRBTT",
    "TTTBBBBBBBBBBTTT",
    "TTTTBSSSSSBBTTTT",
    "TTTTBSSSSSBBTTTT",
    "TTTTTBBBBBBTTTTT",
    "TTTTTTTTTTTTTTTT",
    "TTTTTTTTTTTTTTTT"
]

# --- Blocks (16x16) ---
question_1 = [
    "YPYPYPYPYPYPYPYP",
    "PYPYPYPYPYPYPYPY",
    "YPYPYYDDDDYYPYPY",
    "PYPYDDYYYYDDYPYP",
    "YPYPDDYYYYDDYPYP",
    "PYPYYYYYDDYYYPYP",
    "YPYPYYYDDYYYPYPY",
    "PYPYYDDYYYYYPYPY",
    "YPYPYDDYYYYYPYPY",
    "PYPYPYPYPYPYPYPY",
    "YPYPYDDYYYYYPYPY",
    "PYPYYDDYYYYYPYPY",
    "YPYPYPYPYPYPYPYP",
    "PYBBBYPYPYPYBBBY",
    "YBBBYPYPYPYYBBBY",
    "PYPYPYPYPYPYPYPY"
]
question_2 = [
    "YPYPYPYPYPYPYPYP",
    "PYPYPYPYPYPYPYPY",
    "YPYPYYWWWWYYPYPY",
    "PYPYWWYYYYWWYPYP",
    "YPYPWWYYYYWWYPYP",
    "PYPYYYYYWWYYYPYP",
    "YPYPYYYWWYYYPYPY",
    "PYPYYWWYYYYYPYPY",
    "YPYPYWWYYYYYPYPY",
    "PYPYPYPYPYPYPYPY",
    "YPYPYWWYYYYYPYPY",
    "PYPYYWWYYYYYPYPY",
    "YPYPYPYPYPYPYPYP",
    "PYBBBYPYPYPYBBBY",
    "YBBBYPYPYPYYBBBY",
    "PYPYPYPYPYPYPYPY"
]
empty_block = [
    "DDDDDDDDDDDDDDDD",
    "DLLLLLLLLLLLLLLD",
    "DLLDDDDDDDDDDLLD",
    "DLDDDDDDDDDDDDLD",
    "DLDDDDDDDDDDDDLD",
    "DLDDDDDDDDDDDDLD",
    "DLDDDDDDDDDDDDLD",
    "DLDDDDDDDDDDDDLD",
    "DLDDDDDDDDDDDDLD",
    "DLDDDDDDDDDDDDLD",
    "DLDDDDDDDDDDDDLD",
    "DLDDDDDDDDDDDDLD",
    "DLDDDDDDDDDDDDLD",
    "DLLDDDDDDDDDDLLD",
    "DLLLLLLLLLLLLLLD",
    "DDDDDDDDDDDDDDDD"
]
brick_block = [
    "EEEEEEEEEEEEEEEE",
    "ELLLLLLEELLLLLLE",
    "ELLLLLLEELLLLLLE",
    "ELLLLLLEELLLLLLE",
    "EEEEEEEEEEEEEEEE",
    "LLLEELLLLLLEELLL",
    "LLLEELLLLLLEELLL",
    "LLLEELLLLLLEELLL",
    "EEEEEEEEEEEEEEEE",
    "ELLLLLLEELLLLLLE",
    "ELLLLLLEELLLLLLE",
    "ELLLLLLEELLLLLLE",
    "EEEEEEEEEEEEEEEE",
    "LLLEELLLLLLEELLL",
    "LLLEELLLLLLEELLL",
    "EEEEEEEEEEEEEEEE"
]

# Sprite Sheet Assembly Function
def create_spritesheet(frames, frame_width, frame_height, scale, output_path):
    sheet_width = frame_width * len(frames)
    sheet_height = frame_height
    img = Image.new('RGBA', (sheet_width * scale, sheet_height * scale), (0, 0, 0, 0))
    
    for f_idx, frame in enumerate(frames):
        for y in range(frame_height):
            for x in range(frame_width):
                color_char = frame[y][x]
                color = COLORS.get(color_char, (0, 0, 0, 0))
                # Scale logic
                px = (f_idx * frame_width + x) * scale
                py = y * scale
                for sy in range(scale):
                    for sx in range(scale):
                        img.putpixel((px + sx, py + sy), color)
                        
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    img.save(output_path)
    print(f"Generated {output_path}")

SCALE = 4

create_spritesheet([mario_idle, mario_walk1, mario_walk2, mario_jump], 16, 16, SCALE, 'assets/textures/sprite_sheets/player_sheet.png')
create_spritesheet([goomba_1, goomba_2, koopa_1, koopa_2], 16, 24, SCALE, 'assets/textures/sprite_sheets/enemies_sheet.png')
create_spritesheet([coin_1, coin_2, coin_3, coin_2, mushroom], 16, 16, SCALE, 'assets/textures/sprite_sheets/items_sheet.png')
create_spritesheet([question_1, question_2, empty_block, brick_block], 16, 16, SCALE, 'assets/textures/sprite_sheets/blocks_sheet.png')

# Background (64x32 tile showing classic clouds/hills)
bg = [
    "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC",
    "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC",
    "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC",
    "CCCCCCCCCCWWWWCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC",
    "CCCCCCCWWWWWWWWWWCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC",
    "CCCCCCCWWWWWWWWWWCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC",
    "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCWWWWCCCCCCCCCCCCCCCCCCC",
    "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCWWWWWWWWWWCCCCCCCCCCCCCCCC",
    "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCWWWWWWWWWWCCCCCCCCCCCCCCCC",
    "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC",
    "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC",
    "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC",
    "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC",
    "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC",
    "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC",
    "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC",
    "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC",
    "CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC",
    "CCCCCCCCCCCCCCCCGCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC",
    "CCCCCCCCCCCCCCGGGGGCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC",
    "CCCCCCCCCCCCCGGYYYGGCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC",
    "CCCCCCCCCCCGGGYYYYYGGGCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCGCCCCCCCCCCC",
    "CCCCCCCCCGGGYYYYYYYYYGGGCCCCCCCCCCCCCCCCCCCCCCCCCCGGGGGCCCCCCCCC",
    "CCCCCCCGGGYYYYYYYYYYYYYGGGCCCCCCCCCCCCCCCCCCCCCCGGYGGYYGGCCCCCCC",
    "CCCCCGGGYYYYYYYYYYYYYYYYYGGGCCCCCCCCCCCCCCCCCCGGYYYYYYYYYGGCCCCC",
    "CCCGGGYYYYYYYYYYYYYYYYYYYYYGGGCCCCCCCCCCCCCCGGYYYYYYYYYYYYYGGCCC",
    "GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG",
    "GLLGLLGLLGLLGLLGLLGLLGLLGLLGLLGLLGLLGLLGLLGLLGLLGLLGLLGLLGLLGLLG",
    "LLDDLLDDLLDDLLDDLLDDLLDDLLDDLLDDLLDDLLDDLLDDLLDDLLDDLLDDLLDDLLDD",
    "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD",
    "DLLLLDDDDLLLLDDDDLLLLDDDDLLLLDDDDLLLLDDDDLLLLDDDDLLLLDDDDLLLLDDD",
    "DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD"
]
create_spritesheet([bg], 64, 32, SCALE, 'assets/textures/sprite_sheets/world_bg.png')

print("All true 2D sprite sheets generated successfully.")
