import os
import sys

try:
    from PIL import Image
except ImportError:
    import subprocess
    subprocess.check_call([sys.executable, "-m", "pip", "install", "Pillow"])
    from PIL import Image

# Define color palette
COLORS = {
    'T': (0, 0, 0, 0),        # Transparent
    'B': (0, 0, 0, 255),      # Black
    'R': (255, 0, 0, 255),    # Red
    'O': (255, 128, 0, 255),  # Orange/Brown for shoes/hair
    'Y': (255, 255, 0, 255),  # Yellow
    'S': (255, 204, 153, 255),# Skin
    'U': (0, 0, 255, 255),    # Blue overalls
    'W': (255, 255, 255, 255),# White
    'G': (0, 180, 0, 255),    # Green
    'D': (139, 69, 19, 255),  # Dark Brown
    'L': (205, 133, 63, 255), # Light Brown
    'K': (150, 150, 150, 255),# Dark Gray
    'C': (0, 255, 255, 255),  # Cyan / Sky Blue
}

SPRITES = {}

# 1. Player Idle (16x16)
SPRITES['assets/textures/player/player_idle.png'] = [
    "TTTTTRRRRRTTTTTT",
    "TTTTRRRRRRRRRTTT",
    "TTTTDDSDSSSTTTTT",
    "TTTDSDDSSDSSTTTT",
    "TTTDSDSSDSSSSTTT",
    "TTTDDSSSSDDDDTTT",
    "TTTTTTSSSSSTTTTT",
    "TTTTRRUUURRTTTTT",
    "TTTRRRUUURRRTTTT",
    "TTRRRRUUUURRRRTT",
    "TTSSYRUYURYSSTTT",
    "TTSSSOUUOUUSSTTT",
    "TTTSSUUUUUUSTTTT",
    "TTTTUUUUUUUTTTTT",
    "TTTDDDTTTDDTTTTT",
    "TTDDDDTTTDDDTTTT"
]

# 2. Player Walk (16x16)
SPRITES['assets/textures/player/player_walk_1.png'] = [
    "TTTTTRRRRRTTTTTT",
    "TTTTRRRRRRRRRTTT",
    "TTTTDDSDSSSTTTTT",
    "TTTDSDDSSDSSTTTT",
    "TTTDSDSSDSSSSTTT",
    "TTTDDSSSSDDDDTTT",
    "TTTTTTSSSSSTTTTT",
    "TTTTRRUUUUTTTTTT",
    "TTTRRRUUUUURRTTT",
    "TTRRRRUUUUURRRTT",
    "TTSSYRUYUUUUSSTT",
    "TTSSSOUUUUUSSTTT",
    "TTTSSUUUUUUTTTTT",
    "TTTTTUUUUTTTTTTT",
    "TTTDDDTTDDTTTTTT",
    "TTDDDDTTTDDDTTTT"
]

# 3. Goomba Walk 1 (16x16)
SPRITES['assets/textures/enemies/goomba_walk_1.png'] = [
    "TTTTTTTTTTTTTTTT",
    "TTTTTTTTTTTTTTTT",
    "TTTTTTDDDDTTTTTT",
    "TTTTDDLLLLDDTTTT",
    "TTDDLLLLLLLLDDTT",
    "TDLLBBLLLLBBLLDT",
    "TDLWWBLLLLBWWLDT",
    "TDLWWLLLLLLWWLDT",
    "TDLLLLDDDDLLLLDT",
    "TDLLLLLLLLLLLLDT",
    "TTDDLLLLLLLLDDTT",
    "TTTTDDDDDDDDTTTT",
    "TTTTTSDDDSSTTTTT",
    "TTTTSSDDDSSSTTTT",
    "TTTBBBDDDBBBTTTT",
    "TBBBBBTTTBBBBBTT"
]

# 4. Koopa (16x24)
SPRITES['assets/textures/enemies/koopa_walk_1.png'] = [
    "TTTTTTTTTTTTTTTT",
    "TTTTTTTTTTTTTTTT",
    "TTTTTGGGGGTTTTTT",
    "TTTGGYYYYYGGTTTT",
    "TTGYYYBBBYYYGTTT",
    "TGYYYWWWWBYYYGTT",
    "TGYYYYWWWWYYYGTT",
    "TTGYYYYYYYYYGTTT",
    "TTTGGYYYYYGGTTTT",
    "TTTTGGBBBGGTTTTT",
    "TTTGGGDDDDGGGTTT",
    "TTGGGGDDDGGGGGTT",
    "TGGGGDDDDDDGGGGT",
    "TGGYGGDDDDGGYGGT",
    "TGGYGGDDDDGGYGGT",
    "TGGYYGDDDDGYYGGT",
    "TTGGYYDDDDYYGGTT",
    "TTTGGYDDDDYGGTTT",
    "TTTTGGGGGGGGTTTT",
    "TTTTGGGGGGGGTTTT",
    "TTTTTGGTTGGTTTTT",
    "TTTTTGGTTGGTTTTT",
    "TTTLLLLTTLLLLTTT",
    "TTLLLLLLTLLLLLLT"
]

# 5. Ground Tile (16x16)
SPRITES['assets/textures/terrain_blocks/ground.png'] = [
    "GGGGGGGGGGGGGGGG",
    "GLLGLLGLLGLLGLLG",
    "LLDDLLDDLLDDLLDD",
    "DDDDDDDDDDDDDDDD",
    "DLLLLDDDDLLLLDDD",
    "DLLLLDDDDLLLLDDD",
    "DDDDDDDDDDDDDDDD",
    "DDLLLLDDDDLLLLDD",
    "DDLLLLDDDDLLLLDD",
    "DDDDDDDDDDDDDDDD",
    "DLLLLDDDDLLLLDDD",
    "DLLLLDDDDLLLLDDD",
    "DDDDDDDDDDDDDDDD",
    "DDLLLLDDDDLLLLDD",
    "DDLLLLDDDDLLLLDD",
    "DDDDDDDDDDDDDDDD"
]

# 6. Brick Block (16x16)
SPRITES['assets/textures/terrain_blocks/brick.png'] = [
    "BBBBBBBBBBBBBBBB",
    "BLLLLLLBBLLLLLLB",
    "BLLLLLLBBLLLLLLB",
    "BLLLLLLBBLLLLLLB",
    "BBBBBBBBBBBBBBBB",
    "LLLBBLLLLLLBBLLL",
    "LLLBBLLLLLLBBLLL",
    "LLLBBLLLLLLBBLLL",
    "BBBBBBBBBBBBBBBB",
    "BLLLLLLBBLLLLLLB",
    "BLLLLLLBBLLLLLLB",
    "BLLLLLLBBLLLLLLB",
    "BBBBBBBBBBBBBBBB",
    "LLLBBLLLLLLBBLLL",
    "LLLBBLLLLLLBBLLL",
    "BBBBBBBBBBBBBBBB"
]

# 7. Question Block (16x16)
SPRITES['assets/textures/terrain_blocks/question_1.png'] = [
    "YYYYYYYYYYYYYYYY",
    "YLLLLLLLLLLLLLLY",
    "YLLLLDDDDDLLLLLY",
    "YLLDDLLLLLDDLLLY",
    "YLLDDLLLLLDDLLLY",
    "YLLLLLLLLDDLLLLY",
    "YLLLLLLDDLLLLLLY",
    "YLLLLDDLLLLLLLLY",
    "YLLLLDDLLLLLLLLY",
    "YLLLLLLLLLLLLLLY",
    "YLLLLDDLLLLLLLLY",
    "YLLLLDDLLLLLLLLY",
    "YLLLLLLLLLLLLLLY",
    "YBBBYLLLLLLYBBBY",
    "YBBBYLLLLLLYBBBY",
    "YYYYYYYYYYYYYYYY"
]

# 8. Pipe Top (32x16)
SPRITES['assets/textures/pipes/pipe_top.png'] = [
    "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
    "BGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGB",
    "BGWWGGGGGGGGGGGGGGGGGGGGGGGGGGBB",
    "BGWWGGGGGGGGGGGGGGGGGGGGGGGGGGBB",
    "BGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGB",
    "BGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGB",
    "BGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGB",
    "BGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGB",
    "BGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGB",
    "BGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGB",
    "BGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGB",
    "BGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGB",
    "BGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGB",
    "BGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGB",
    "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
    "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT"
]

# 9. Pipe Body (32x16)
SPRITES['assets/textures/pipes/pipe_body.png'] = [
    "TTBBBBBBBBBBBBBBBBBBBBBBBBBBBBTT",
    "TTBGGGGGGGGGGGGGGGGGGGGGGGGGGBTT",
    "TTBGWWGGGGGGGGGGGGGGGGGGGGGGGBTT",
    "TTBGWWGGGGGGGGGGGGGGGGGGGGGGGBTT",
    "TTBGGGGGGGGGGGGGGGGGGGGGGGGGGBTT",
    "TTBGGGGGGGGGGGGGGGGGGGGGGGGGGBTT",
    "TTBGGGGGGGGGGGGGGGGGGGGGGGGGGBTT",
    "TTBGGGGGGGGGGGGGGGGGGGGGGGGGGBTT",
    "TTBGGGGGGGGGGGGGGGGGGGGGGGGGGBTT",
    "TTBGGGGGGGGGGGGGGGGGGGGGGGGGGBTT",
    "TTBGGGGGGGGGGGGGGGGGGGGGGGGGGBTT",
    "TTBGGGGGGGGGGGGGGGGGGGGGGGGGGBTT",
    "TTBGGGGGGGGGGGGGGGGGGGGGGGGGGBTT",
    "TTBGGGGGGGGGGGGGGGGGGGGGGGGGGBTT",
    "TTBGGGGGGGGGGGGGGGGGGGGGGGGGGBTT",
    "TTBBBBBBBBBBBBBBBBBBBBBBBBBBBBTT"
]

# 10. Coin (16x16)
SPRITES['assets/textures/collectibles/coin_1.png'] = [
    "TTTTTTYYYYTTTTTT",
    "TTTTYYYYYYYYTTTT",
    "TTTYYTTYYTTYYTTT",
    "TTYYTTTYYTTTYYTT",
    "TTYYTTTYYTTTYYTT",
    "TYYTTTTYYTTTTYYT",
    "TYYTTTTYYTTTTYYT",
    "TYYTTTTYYTTTTYYT",
    "TYYTTTTYYTTTTYYT",
    "TYYTTTTYYTTTTYYT",
    "TYYTTTTYYTTTTYYT",
    "TTYYTTTYYTTTYYTT",
    "TTYYTTTYYTTTYYTT",
    "TTTYYTTYYTTYYTTT",
    "TTTTYYYYYYYYTTTT",
    "TTTTTTYYYYTTTTTT"
]

# 11. Mushroom (16x16)
SPRITES['assets/textures/collectibles/mushroom.png'] = [
    "TTTTTTTTTTTTTTTT",
    "TTTTTTBBBBTTTTTT",
    "TTTTBBRRRRBBTTTT",
    "TTTBRRRRRRRRBTTT",
    "TTBRRWWWWWWWRBTT",
    "TBRRWWWWWWWWWRBT",
    "TBRRWWWWWWWWWRBT",
    "TBRRWWWWWWWWWRBT",
    "TBRRRWWWWWWWRRBT",
    "TBRRRRRRRRRRRRBT",
    "TTBRRRRRRRRRRBTT",
    "TTTBBBBBBBBBBTTT",
    "TTTTBSSSSSBBTTTT",
    "TTTTBSSSSSBBTTTT",
    "TTTTTBBBBBBTTTTT",
    "TTTTTTTTTTTTTTTT"
]

# 12. Background (16x16 repeating tile)
SPRITES['assets/textures/backgrounds/sky_bg.png'] = [
    "CCCCCCCCCCCCCCCC",
    "CCCCCCCCCCCCCCCC",
    "CCCCCCCCCCCCCCCC",
    "CCCCCCCCCCCCCCCC",
    "CCCCCCCCCCCCCCCC",
    "CCCCCCCCCCCCCCCC",
    "CCCCCCCCCCCCCCCC",
    "CCCCCCCCCCCCCCCC",
    "CCCCCCCCCCCCCCCC",
    "CCCCCCCCCCCCCCCC",
    "CCCCCCCCCCCCCCCC",
    "CCCCCCCCCCCCCCCC",
    "CCCCCCCCCCCCCCCC",
    "CCCCCCCCCCCCCCCC",
    "CCCCCCCCCCCCCCCC",
    "CCCCCCCCCCCCCCCC"
]


SCALE = 4  # Scale up the 16x16 to 64x64 for modern screens

for path, pixels in SPRITES.items():
    width = len(pixels[0])
    height = len(pixels)
    
    img = Image.new('RGBA', (width * SCALE, height * SCALE), (0, 0, 0, 0))
    for y in range(height):
        for x in range(width):
            color_char = pixels[y][x]
            color = COLORS.get(color_char, (0, 0, 0, 0))
            
            # Draw a SCALE x SCALE block
            for sy in range(SCALE):
                for sx in range(SCALE):
                    img.putpixel((x * SCALE + sx, y * SCALE + sy), color)
                    
    # Ensure directory exists
    os.makedirs(os.path.dirname(path), exist_ok=True)
    img.save(path)
    print(f"Generated {path}")

print("All true 2D pixel-art assets generated successfully.")
